export const eventsPatterns = {
    POST_LIKED: 'POST.LIKED',
    POST_COMMENTED: 'POST.COMMENTED',
    POST_SHARED: 'POST.SHARED',
    FRIEND_REQUEST_SENT: 'FRIEND.REQUEST.SENT',
    FRIEND_REQUEST_ACCEPTED: 'FRIEND.REQUEST.ACCEPTED',
    APPLICATION_STATUS_CHANGED: 'APPLICATION.STATUS.CHANGED',
    NEW_JOB_APPLICATION: 'JOB.APPLICATION.NEW',
    MESSAGE_RECIEVED: 'MESSAGE.RECEIVED',
}